import {
  UserProfile,
  AttendanceRecord,
  LeaveRecord,
  PayrollRecord,
  Notification,
} from "./types";

// ─── Users / Employees ───────────────────────────────────────────────────────

export const MOCK_USERS: UserProfile[] = [
  {
    uid: "admin-001",
    fullName: "Sarah Mitchell",
    employeeId: "HR001",
    email: "admin@dayflow.com",
    role: "admin",
    phone: "+1 555-0101",
    address: "101 Corporate Drive, San Francisco, CA",
    department: "Human Resources",
    designation: "HR Manager",
    joiningDate: "2022-01-15",
    employmentType: "Full-time",
    profilePicture: "",
    emailVerified: true,
  },
  {
    uid: "emp-001",
    fullName: "James Carter",
    employeeId: "EMP001",
    email: "james@dayflow.com",
    role: "employee",
    phone: "+1 555-0102",
    address: "22 Oak Street, Austin, TX",
    department: "Engineering",
    designation: "Software Engineer",
    joiningDate: "2023-03-01",
    employmentType: "Full-time",
    profilePicture: "",
    emailVerified: true,
  },
  {
    uid: "emp-002",
    fullName: "Priya Sharma",
    employeeId: "EMP002",
    email: "priya@dayflow.com",
    role: "employee",
    phone: "+1 555-0103",
    address: "88 Maple Ave, New York, NY",
    department: "Design",
    designation: "UI/UX Designer",
    joiningDate: "2023-06-15",
    employmentType: "Full-time",
    profilePicture: "",
    emailVerified: true,
  },
  {
    uid: "emp-003",
    fullName: "Daniel Lee",
    employeeId: "EMP003",
    email: "daniel@dayflow.com",
    role: "employee",
    phone: "+1 555-0104",
    address: "56 Pine Road, Seattle, WA",
    department: "Engineering",
    designation: "Backend Developer",
    joiningDate: "2022-11-10",
    employmentType: "Full-time",
    profilePicture: "",
    emailVerified: true,
  },
  {
    uid: "emp-004",
    fullName: "Olivia Thompson",
    employeeId: "EMP004",
    email: "olivia@dayflow.com",
    role: "employee",
    phone: "+1 555-0105",
    address: "34 Birch Lane, Denver, CO",
    department: "Marketing",
    designation: "Marketing Specialist",
    joiningDate: "2024-01-20",
    employmentType: "Part-time",
    profilePicture: "",
    emailVerified: true,
  },
  {
    uid: "emp-005",
    fullName: "Marcus Johnson",
    employeeId: "EMP005",
    email: "marcus@dayflow.com",
    role: "employee",
    phone: "+1 555-0106",
    address: "77 Elm Street, Chicago, IL",
    department: "Finance",
    designation: "Financial Analyst",
    joiningDate: "2023-09-05",
    employmentType: "Full-time",
    profilePicture: "",
    emailVerified: true,
  },
];

// ─── Attendance ───────────────────────────────────────────────────────────────

const today = new Date().toISOString().split("T")[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split("T")[0];
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString().split("T")[0];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-001",
    userId: "emp-001",
    employeeId: "EMP001",
    employeeName: "James Carter",
    date: today,
    checkInTime: "09:02",
    checkOutTime: null,
    totalWorkingHours: null,
    status: "Present",
  },
  {
    id: "att-002",
    userId: "emp-001",
    employeeId: "EMP001",
    employeeName: "James Carter",
    date: yesterday,
    checkInTime: "09:15",
    checkOutTime: "18:10",
    totalWorkingHours: "8.92",
    status: "Present",
  },
  {
    id: "att-003",
    userId: "emp-001",
    employeeId: "EMP001",
    employeeName: "James Carter",
    date: twoDaysAgo,
    checkInTime: "09:30",
    checkOutTime: "13:45",
    totalWorkingHours: "4.25",
    status: "Half-day",
  },
  {
    id: "att-004",
    userId: "emp-002",
    employeeId: "EMP002",
    employeeName: "Priya Sharma",
    date: today,
    checkInTime: "08:55",
    checkOutTime: "17:55",
    totalWorkingHours: "9.0",
    status: "Present",
  },
  {
    id: "att-005",
    userId: "emp-002",
    employeeId: "EMP002",
    employeeName: "Priya Sharma",
    date: yesterday,
    checkInTime: "09:00",
    checkOutTime: "18:00",
    totalWorkingHours: "9.0",
    status: "Present",
  },
  {
    id: "att-006",
    userId: "emp-003",
    employeeId: "EMP003",
    employeeName: "Daniel Lee",
    date: today,
    checkInTime: null,
    checkOutTime: null,
    totalWorkingHours: null,
    status: "Leave",
  },
  {
    id: "att-007",
    userId: "emp-004",
    employeeId: "EMP004",
    employeeName: "Olivia Thompson",
    date: today,
    checkInTime: "10:05",
    checkOutTime: "14:10",
    totalWorkingHours: "4.08",
    status: "Half-day",
  },
  {
    id: "att-008",
    userId: "emp-005",
    employeeId: "EMP005",
    employeeName: "Marcus Johnson",
    date: today,
    checkInTime: "09:00",
    checkOutTime: "18:00",
    totalWorkingHours: "9.0",
    status: "Present",
  },
];

// ─── Leaves ───────────────────────────────────────────────────────────────────

export const MOCK_LEAVES: LeaveRecord[] = [
  {
    id: "lv-001",
    userId: "emp-001",
    employeeId: "EMP001",
    employeeName: "James Carter",
    leaveType: "Sick Leave",
    startDate: "2026-08-28",
    endDate: "2026-08-29",
    remarks: "Not feeling well, doctor's appointment.",
    status: "Pending",
    adminComment: "",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "lv-002",
    userId: "emp-003",
    employeeId: "EMP003",
    employeeName: "Daniel Lee",
    leaveType: "Paid Leave",
    startDate: "2026-08-22",
    endDate: "2026-08-24",
    remarks: "Family vacation.",
    status: "Approved",
    adminComment: "Approved. Enjoy your time off!",
    createdAt: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: "lv-003",
    userId: "emp-002",
    employeeId: "EMP002",
    employeeName: "Priya Sharma",
    leaveType: "Unpaid Leave",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    remarks: "Personal matter.",
    status: "Rejected",
    adminComment: "Denied due to project deadline. Please reschedule.",
    createdAt: new Date(Date.now() - 1209600000).toISOString(),
  },
  {
    id: "lv-004",
    userId: "emp-004",
    employeeId: "EMP004",
    employeeName: "Olivia Thompson",
    leaveType: "Sick Leave",
    startDate: "2026-08-30",
    endDate: "2026-08-30",
    remarks: "Medical checkup.",
    status: "Pending",
    adminComment: "",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

// ─── Payroll ──────────────────────────────────────────────────────────────────

export const MOCK_PAYROLL: PayrollRecord[] = [
  {
    id: "pay-001",
    userId: "emp-001",
    employeeId: "EMP001",
    month: "2026-08",
    basicSalary: 7000,
    allowances: 1500,
    deductions: 800,
    netSalary: 7700,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pay-002",
    userId: "emp-001",
    employeeId: "EMP001",
    month: "2026-07",
    basicSalary: 7000,
    allowances: 1500,
    deductions: 700,
    netSalary: 7800,
    createdAt: new Date(Date.now() - 2592000000).toISOString(),
  },
  {
    id: "pay-003",
    userId: "emp-002",
    employeeId: "EMP002",
    month: "2026-08",
    basicSalary: 6000,
    allowances: 1200,
    deductions: 600,
    netSalary: 6600,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pay-004",
    userId: "emp-003",
    employeeId: "EMP003",
    month: "2026-08",
    basicSalary: 8000,
    allowances: 2000,
    deductions: 1000,
    netSalary: 9000,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pay-005",
    userId: "emp-004",
    employeeId: "EMP004",
    month: "2026-08",
    basicSalary: 4000,
    allowances: 500,
    deductions: 300,
    netSalary: 4200,
    createdAt: new Date().toISOString(),
  },
  {
    id: "pay-006",
    userId: "emp-005",
    employeeId: "EMP005",
    month: "2026-08",
    basicSalary: 7500,
    allowances: 1800,
    deductions: 900,
    netSalary: 8400,
    createdAt: new Date().toISOString(),
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-001",
    userId: "emp-003",
    title: "Leave Request Approved",
    message: "Your Paid Leave request from Aug 22 to Aug 24 has been approved. Enjoy your time off!",
    type: "leave_update",
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "notif-002",
    userId: "emp-002",
    title: "Leave Request Rejected",
    message: "Your Unpaid Leave request from Jul 10 to Jul 12 has been rejected. Denied due to project deadline. Please reschedule.",
    type: "leave_update",
    isRead: true,
    createdAt: new Date(Date.now() - 1209600000).toISOString(),
  },
  {
    id: "notif-003",
    userId: "emp-001",
    title: "Welcome to Dayflow!",
    message: "Your account is all set up. Start by checking in for today!",
    type: "system",
    isRead: false,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];
