"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
} from "@/components/ui/card";
import { toast } from "sonner";
import { Eye, EyeOff, Loader2, Upload, Building2, CheckCircle2 } from "lucide-react";

export default function RegisterPage() {
  const router = useRouter();
  const { register } = useAuth();
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [logoName, setLogoName] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    companyName: "",
    name: "",
    email: "",
    phone: "",
    password: "",
    confirmPassword: "",
  });

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setLogoName(e.target.files[0].name);
      toast.success(`Logo "${e.target.files[0].name}" selected!`);
    }
  };

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.companyName.trim()) {
      toast.error("Company Name is required.");
      return;
    }
    if (!formData.name.trim()) {
      toast.error("Name is required.");
      return;
    }
    if (formData.password.length < 6) {
      toast.error("Password must be at least 6 characters.");
      return;
    }
    if (formData.password !== formData.confirmPassword) {
      toast.error("Passwords do not match. Please verify.");
      return;
    }

    setLoading(true);
    try {
      const user = await register({
        fullName: formData.name.trim(),
        employeeId: "", // Will be auto-generated by backend based on formula
        email: formData.email.trim(),
        role: "admin",
        password: formData.password,
      });

      toast.success(`Company registered successfully! Welcome, ${user.fullName}!`);
      router.push("/dashboard");
    } catch (error: any) {
      toast.error(error.message || "Failed to register company.");
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData((prev) => ({ ...prev, [e.target.id]: e.target.value }));
  };

  return (
    <div className="flex min-h-screen w-full items-center justify-center bg-zinc-950 p-4 py-10">
      <div className="w-full max-w-lg space-y-5">
        {/* App / Web Logo Container */}
        <div className="text-center">
          <div className="inline-flex items-center justify-center p-2.5 rounded-2xl bg-purple-600/10 border border-purple-500/20 mb-3 shadow-lg shadow-purple-900/20">
            <img src="/logo.png" alt="Dayflow Logo" className="h-12 w-12 object-contain" />
          </div>
          <h1 className="text-3xl font-bold text-white tracking-tight">
            Day<span className="text-purple-500">flow</span> <span className="text-sm font-normal text-zinc-400 bg-zinc-900 px-2 py-0.5 rounded-full border border-zinc-800 ml-1">HRMS</span>
          </h1>
          <p className="text-zinc-400 text-xs mt-1">Human Resource Management System</p>
        </div>

        {/* Sign Up Card */}
        <Card className="bg-zinc-900 border-zinc-800 text-zinc-100 shadow-xl">
          <CardHeader className="text-center pb-3">
            <h2 className="text-xl font-bold text-white">Sign Up</h2>
            <p className="text-xs text-zinc-400">Register your organization & create admin account</p>
          </CardHeader>
          <form onSubmit={handleRegister}>
            <CardContent className="space-y-4 pt-1">
              {/* Company Name + Upload Logo */}
              <div className="space-y-2">
                <Label htmlFor="companyName" className="text-zinc-300 font-medium text-sm">
                  Company Name :-
                </Label>
                <div className="flex items-center gap-2">
                  <Input
                    id="companyName"
                    required
                    placeholder="e.g. Odoo India Pvt Ltd"
                    value={formData.companyName}
                    onChange={handleChange}
                    className="bg-zinc-950 border-zinc-800 text-white placeholder:text-zinc-600 focus-visible:ring-purple-600 h-10 flex-1"
                  />
                  <label
                    htmlFor="logo-upload"
                    className="cursor-pointer inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-md bg-purple-600/15 border border-purple-500/30 text-purple-300 hover:bg-purple-600/25 hover:border-purple-500/50 text-xs font-medium transition-colors whitespace-nowrap h-10"
                    title="Upload Company Logo"
                  >
                    <Upload className="h-4 w-4" />
                    {logoName ? "Logo Attached" : "Upload Logo"}
                  </label>
                  <input
                    id="logo-upload"
                    type="file"
                    accept="image/*"
                    className="hidden"
                    onChange={handleLogoUpload}
                  />
                </div>
                {logoName && (
                  <p className="text-[11px] text-green-400 flex items-center gap-1 mt-1">
                    <CheckCircle2 className="h-3 w-3" /> {logoName}
                  </p>
                )}
              </div>

              {/* Name Field */}
              <div className="space-y-2">
                <Label htmlFor="name" className="text-zinc-300 font-medium text-sm">
                  Name :-
                </Label>
                <Input
                  id="name"
                  required
                  placeholder="e.g. John Doe"
                  value={formData.name}
                  onChange={handleChange}
                  className="bg-zinc-950 border-zinc-800 text-white placeholder:text-zinc-600 focus-visible:ring-purple-600 h-10"
                />
              </div>

              {/* Email Field */}
              <div className="space-y-2">
                <Label htmlFor="email" className="text-zinc-300 font-medium text-sm">
                  Email :-
                </Label>
                <Input
                  id="email"
                  type="email"
                  required
                  placeholder="admin@company.com"
                  value={formData.email}
                  onChange={handleChange}
                  className="bg-zinc-950 border-zinc-800 text-white placeholder:text-zinc-600 focus-visible:ring-purple-600 h-10"
                />
              </div>

              {/* Phone Field */}
              <div className="space-y-2">
                <Label htmlFor="phone" className="text-zinc-300 font-medium text-sm">
                  Phone :-
                </Label>
                <Input
                  id="phone"
                  type="tel"
                  placeholder="+91 98765 43210"
                  value={formData.phone}
                  onChange={handleChange}
                  className="bg-zinc-950 border-zinc-800 text-white placeholder:text-zinc-600 focus-visible:ring-purple-600 h-10"
                />
              </div>

              {/* Password Field */}
              <div className="space-y-2">
                <Label htmlFor="password" className="text-zinc-300 font-medium text-sm">
                  Password :-
                </Label>
                <div className="relative">
                  <Input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    required
                    minLength={6}
                    placeholder="••••••••"
                    value={formData.password}
                    onChange={handleChange}
                    className="bg-zinc-950 border-zinc-800 text-white placeholder:text-zinc-600 focus-visible:ring-purple-600 pr-10 h-10"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300 p-1"
                  >
                    {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                  </button>
                </div>
              </div>

              {/* Confirm Password Field */}
              <div className="space-y-2">
                <Label htmlFor="confirmPassword" className="text-zinc-300 font-medium text-sm">
                  Confirm Password :-
                </Label>
                <div className="relative">
                  <Input
                    id="confirmPassword"
                    type={showConfirmPassword ? "text" : "password"}
                    required
                    minLength={6}
                    placeholder="••••••••"
                    value={formData.confirmPassword}
                    onChange={handleChange}
                    className="bg-zinc-950 border-zinc-800 text-white placeholder:text-zinc-600 focus-visible:ring-purple-600 pr-10 h-10"
                  />
                  <button
                    type="button"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300 p-1"
                  >
                    {showConfirmPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                  </button>
                </div>
              </div>
            </CardContent>

            <CardFooter className="flex flex-col space-y-4 pt-2">
              {/* Sign Up Button */}
              <Button
                type="submit"
                className="w-full bg-gradient-to-r from-purple-600 to-fuchsia-600 hover:from-purple-700 hover:to-fuchsia-700 text-white font-semibold h-11 text-sm tracking-wide transition-all shadow-md shadow-purple-900/30"
                disabled={loading}
              >
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Sign Up
              </Button>

              {/* Already have an account ? Sign In */}
              <div className="text-center text-sm text-zinc-400">
                Already have an account ?{" "}
                <Link
                  href="/login"
                  className="text-purple-400 hover:text-purple-300 font-medium underline underline-offset-4"
                >
                  Sign In
                </Link>
              </div>
            </CardFooter>
          </form>
        </Card>
      </div>
    </div>
  );
}
