"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { Eye, EyeOff, Loader2, Upload, CheckCircle2 } from "lucide-react";

export default function RegisterPage() {
  const router = useRouter();
  const { register } = useAuth();
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [logoName, setLogoName] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    companyName: "",
    name: "",
    email: "",
    phone: "",
    password: "",
    confirmPassword: "",
  });

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setLogoName(e.target.files[0].name);
      toast.success(`Logo "${e.target.files[0].name}" selected!`);
    }
  };

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.companyName.trim()) {
      toast.error("Company Name is required.");
      return;
    }
    if (!formData.name.trim()) {
      toast.error("Name is required.");
      return;
    }
    if (formData.password.length < 6) {
      toast.error("Password must be at least 6 characters.");
      return;
    }
    if (formData.password !== formData.confirmPassword) {
      toast.error("Passwords do not match. Please verify.");
      return;
    }

    setLoading(true);
    try {
      const user = await register({
        fullName: formData.name.trim(),
        employeeId: "", // Will be auto-generated by backend based on formula
        email: formData.email.trim(),
        role: "admin",
        password: formData.password,
      });

      toast.success(`Company registered successfully! Welcome, ${user.fullName}!`);
      router.push("/dashboard");
    } catch (error: any) {
      toast.error(error.message || "Failed to register company.");
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData((prev) => ({ ...prev, [e.target.id]: e.target.value }));
  };

  return (
    <main className="relative min-h-screen w-full flex flex-col items-center justify-center bg-black text-zinc-100 selection:bg-purple-600 selection:text-white overflow-hidden">
      {/* ─── Full-Bleed Video Background ──────────────────────────────── */}
      <div className="fixed inset-0 w-full h-full overflow-hidden bg-black pointer-events-none" style={{ zIndex: 0 }}>
        <video
          className="absolute inset-0 w-full h-full object-cover"
          style={{ opacity: 0.45 }}
          autoPlay
          muted
          loop
          playsInline
        >
          <source
            src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260809_012548_ef22562c-c0ae-4816-ad9d-f8922af4e6a7.mp4"
            type="video/mp4"
          />
        </video>
        {/* Dark overlay for readability */}
        <div className="absolute inset-0 bg-gradient-to-b from-black/70 via-black/50 to-black/80" />
      </div>

      {/* ─── Main Content ─────────────────────────────────────────────── */}
      <div className="relative w-full max-w-[460px] mx-auto px-4 py-8" style={{ zIndex: 1 }}>
        {/* ─── Header / Branding ─────────────────────────────────────── */}
        <header
          className="text-center mb-6"
          style={{
            animation: "fadeSlideIn 0.7s cubic-bezier(0.22, 1, 0.36, 1) both",
          }}
        >
          <div className="flex items-center justify-center gap-2 mb-2">
            <h1 className="text-3xl font-bold tracking-tight dayflow-title">
              <span className="dayflow-shimmer">Day</span>
              <span className="dayflow-shimmer-accent">flow</span>
            </h1>
            <span className="text-[10px] font-semibold tracking-wider text-amber-300/80 bg-amber-950/40 border border-amber-700/40 px-2 py-0.5 rounded-md">
              HRMS
            </span>
          </div>
          <p className="text-xs text-zinc-400 mt-1 font-normal">
            Human Resource Management System
          </p>
        </header>

        {/* ─── Sign Up Card ──────────────────────────────────────────── */}
        <section
          className="rounded-2xl bg-zinc-900/80 border border-zinc-800/60 p-7 sm:p-8 shadow-2xl backdrop-blur-md"
          style={{
            animation: "fadeSlideUp 0.85s cubic-bezier(0.22, 1, 0.36, 1) 0.1s both",
          }}
        >
          <div className="mb-5">
            <h2 className="text-lg font-semibold text-white">Create your account</h2>
            <p className="text-xs text-zinc-400 mt-1">
              Register your organization &amp; create admin access
            </p>
          </div>

          <form onSubmit={handleRegister} className="space-y-4">
            {/* Company Name + Upload Logo */}
            <div className="space-y-1.5">
              <Label htmlFor="companyName" className="text-xs font-medium text-zinc-300 block">
                Company Name
              </Label>
              <div className="flex items-center gap-2">
                <Input
                  id="companyName"
                  required
                  placeholder="e.g. Odoo India Pvt Ltd"
                  value={formData.companyName}
                  onChange={handleChange}
                  className="h-10 rounded-lg bg-zinc-950/80 border-zinc-800 px-3.5 text-sm text-white placeholder:text-zinc-500 focus-visible:border-purple-500 focus-visible:ring-1 focus-visible:ring-purple-500 transition-colors flex-1"
                />
                <label
                  htmlFor="logo-upload"
                  className="cursor-pointer inline-flex items-center justify-center gap-1.5 px-3 h-10 rounded-lg bg-purple-600/15 border border-purple-500/30 text-purple-300 hover:bg-purple-600/25 hover:border-purple-500/50 text-xs font-medium transition-colors whitespace-nowrap"
                  title="Upload Company Logo"
                >
                  <Upload className="h-3.5 w-3.5" />
                  {logoName ? "Attached" : "Logo"}
                </label>
                <input
                  id="logo-upload"
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={handleLogoUpload}
                />
              </div>
              {logoName && (
                <p className="text-[11px] text-green-400 flex items-center gap-1 mt-0.5">
                  <CheckCircle2 className="h-3 w-3" /> {logoName}
                </p>
              )}
            </div>

            {/* Name */}
            <div className="space-y-1.5">
              <Label htmlFor="name" className="text-xs font-medium text-zinc-300 block">
                Full Name
              </Label>
              <Input
                id="name"
                required
                placeholder="e.g. John Doe"
                value={formData.name}
                onChange={handleChange}
                className="h-10 rounded-lg bg-zinc-950/80 border-zinc-800 px-3.5 text-sm text-white placeholder:text-zinc-500 focus-visible:border-purple-500 focus-visible:ring-1 focus-visible:ring-purple-500 transition-colors"
              />
            </div>

            {/* Email */}
            <div className="space-y-1.5">
              <Label htmlFor="email" className="text-xs font-medium text-zinc-300 block">
                Email
              </Label>
              <Input
                id="email"
                type="email"
                required
                placeholder="admin@company.com"
                value={formData.email}
                onChange={handleChange}
                className="h-10 rounded-lg bg-zinc-950/80 border-zinc-800 px-3.5 text-sm text-white placeholder:text-zinc-500 focus-visible:border-purple-500 focus-visible:ring-1 focus-visible:ring-purple-500 transition-colors"
              />
            </div>

            {/* Phone */}
            <div className="space-y-1.5">
              <Label htmlFor="phone" className="text-xs font-medium text-zinc-300 block">
                Phone
              </Label>
              <Input
                id="phone"
                type="tel"
                placeholder="+91 98765 43210"
                value={formData.phone}
                onChange={handleChange}
                className="h-10 rounded-lg bg-zinc-950/80 border-zinc-800 px-3.5 text-sm text-white placeholder:text-zinc-500 focus-visible:border-purple-500 focus-visible:ring-1 focus-visible:ring-purple-500 transition-colors"
              />
            </div>

            {/* Password */}
            <div className="space-y-1.5">
              <Label htmlFor="password" className="text-xs font-medium text-zinc-300 block">
                Password
              </Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  required
                  minLength={6}
                  placeholder="••••••••"
                  value={formData.password}
                  onChange={handleChange}
                  className="h-10 rounded-lg bg-zinc-950/80 border-zinc-800 pl-3.5 pr-11 text-sm text-white placeholder:text-zinc-500 focus-visible:border-purple-500 focus-visible:ring-1 focus-visible:ring-purple-500 transition-colors"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-400 hover:text-zinc-200 transition-colors p-1"
                  aria-label={showPassword ? "Hide password" : "Show password"}
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>

            {/* Confirm Password */}
            <div className="space-y-1.5">
              <Label htmlFor="confirmPassword" className="text-xs font-medium text-zinc-300 block">
                Confirm Password
              </Label>
              <div className="relative">
                <Input
                  id="confirmPassword"
                  type={showConfirmPassword ? "text" : "password"}
                  required
                  minLength={6}
                  placeholder="••••••••"
                  value={formData.confirmPassword}
                  onChange={handleChange}
                  className="h-10 rounded-lg bg-zinc-950/80 border-zinc-800 pl-3.5 pr-11 text-sm text-white placeholder:text-zinc-500 focus-visible:border-purple-500 focus-visible:ring-1 focus-visible:ring-purple-500 transition-colors"
                />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-400 hover:text-zinc-200 transition-colors p-1"
                  aria-label={showConfirmPassword ? "Hide password" : "Show password"}
                >
                  {showConfirmPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>

            {/* Create Account Button */}
            <Button
              type="submit"
              disabled={loading}
              className="w-full h-11 mt-2 rounded-lg bg-gradient-to-r from-amber-500 via-orange-500 to-rose-500 hover:from-amber-400 hover:via-orange-400 hover:to-rose-400 text-white font-semibold text-sm transition-all shadow-lg shadow-amber-900/40 hover:-translate-y-px"
            >
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Create Account
            </Button>

            {/* Sign In Link */}
            <div className="pt-1 text-center text-xs text-zinc-400">
              Already have an account?{" "}
              <Link
                href="/login"
                className="text-amber-400 hover:text-amber-300 font-medium ml-1 transition-colors"
              >
                Sign in
              </Link>
            </div>
          </form>
        </section>
      </div>

      {/* ─── Entrance Animations ──────────────────────────────────────── */}
      <style jsx global>{`
        @keyframes fadeSlideIn {
          from {
            opacity: 0;
            transform: translateY(-14px);
            filter: blur(4px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
            filter: blur(0);
          }
        }
        @keyframes fadeSlideUp {
          from {
            opacity: 0;
            transform: translateY(18px) scale(0.98);
            filter: blur(6px);
          }
          to {
            opacity: 1;
            transform: translateY(0) scale(1);
            filter: blur(0);
          }
        }
        @keyframes shimmer {
          0% {
            background-position: -200% center;
          }
          100% {
            background-position: 200% center;
          }
        }
        .dayflow-shimmer {
          background: linear-gradient(
            90deg,
            #ffffff 0%,
            #e2c6ff 25%,
            #ffffff 50%,
            #ffd6a0 75%,
            #ffffff 100%
          );
          background-size: 200% auto;
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
          animation: shimmer 3s ease-in-out infinite;
        }
        .dayflow-shimmer-accent {
          background: linear-gradient(
            90deg,
            #f59e0b 0%,
            #f97316 25%,
            #fbbf24 50%,
            #f97316 75%,
            #f59e0b 100%
          );
          background-size: 200% auto;
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
          animation: shimmer 3s ease-in-out infinite;
          animation-delay: 0.5s;
        }
        @media (prefers-reduced-motion: reduce) {
          * {
            animation-duration: 0.01ms !important;
            animation-iteration-count: 1 !important;
          }
          .dayflow-shimmer {
            -webkit-text-fill-color: #ffffff;
          }
          .dayflow-shimmer-accent {
            -webkit-text-fill-color: #f59e0b;
          }
        }
      `}</style>
    </main>
  );
}
